'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Recycle, Sparkles } from 'lucide-react'

const stages = [
  { number: '01', title: 'Collected', body: 'We work with waste management partners to gather processed plastic that is ready for a new purpose.', image: '/images/waste-collection.png', alt: 'Workers sorting processed plastic at a collection center', note: 'Waste partners / across India' },
  { number: '02', title: 'Cleaned', body: 'Materials are sorted by polymer, washed, and checked so every colour and texture can perform beautifully.', image: '/images/material-lab.png', alt: 'Recycled plastic flakes and material samples in a lab', note: 'Material lab / quality check' },
  { number: '03', title: 'Reformed', body: 'Plastic becomes strong, colourful filament — the raw material for our small, precise 3D builds.', image: '/images/material-lab.png', alt: 'Recycled plastic filament spools in a studio', note: 'Filament / rPET + PLA' },
  { number: '04', title: 'Played', body: 'Makers print, inspect, and finish each piece until it is ready to carry a story into someone’s hands.', image: '/images/print-studio.png', alt: 'A 3D printer creating a colorful toy', note: 'Print studio / made with care' },
]

export default function OurLoopPage() {
  return <main className="loop-page"><div className="announcement"><Sparkles size={15} /> Every ReToy India build begins with a second life.</div><header className="site-header loop-header"><Link className="brand" href="/"><span className="brand-mark"><i /><i /><i /><i /></span><span>ReToy India<small>PLAY / REIMAGINED</small></span></Link><Link className="text-link" href="/"><ArrowLeft size={15} /> Back home</Link></header><section className="loop-hero section-pad"><div><p className="eyebrow"><Recycle size={14} /> Our material loop</p><h1>From waste<br /><em>to wonder.</em></h1><p>Nothing begins as a toy. It begins as a choice to see value where others see an ending. Here is the journey behind every ReToy India build.</p></div><div className="loop-hero-image"><Image src="/images/heritage-play.png" alt="A heritage miniature inspired by Hampi temple architecture" fill sizes="(max-width: 900px) 100vw, 45vw" /><span>HISTORY, REBUILT / 2026</span></div></section><section className="loop-statement section-pad"><p className="eyebrow">A visible promise</p><h2>We make the journey<br /><em>part of the play.</em></h2><div className="loop-stat-grid"><div><strong>6.2k kg</strong><span>plastic redirected</span></div><div><strong>4</strong><span>steps to play</span></div><div><strong>100%</strong><span>traceable materials</span></div></div></section><section className="loop-stages section-pad"><div className="section-heading"><div><p className="eyebrow">The four movements</p><h2>Material with<br /><em>memory.</em></h2></div><p className="heading-note">Every stage is part of the design. Every maker adds a little more care.</p></div><div className="loop-stage-grid">{stages.map((stage) => <article className="loop-stage" key={stage.number}><div className="loop-stage-image"><Image src={stage.image} alt={stage.alt} fill sizes="(max-width: 900px) 100vw, 25vw" /><span>{stage.number}</span></div><p className="eyebrow">{stage.note}</p><h3>{stage.title}</h3><p>{stage.body}</p></article>)}</div></section><section className="loop-close section-pad"><div><p className="eyebrow">Keep looking closer</p><h2>A better material<br /><em>makes better play.</em></h2><p>Explore the objects that came through this loop, or imagine one of your own.</p><div className="hero-actions"><Link className="button button-dark" href="/#shop">Explore the shelf <ArrowRight size={17} /></Link><Link className="text-link" href="/#custom-lab">Build a custom story <ArrowRight size={15} /></Link></div></div><div className="loop-seal"><Recycle size={40} /><span>CIRCULAR<br />BY DESIGN</span></div></section><footer className="site-footer"><div className="footer-bottom"><span>© 2026 ReToy India Studio. Made for curious hands.</span><Link href="/">Return to ReToy India</Link></div></footer></main>
}
